export const PortfolioData = [
    {
    image: '/cclub.jpg',
    imageAlt: 'C.Club Landing Page',
    title: 'C.Club',
    subtitle: "Landing page for Claire's rewards program",
    blurb1: "Created while at Claire's",
    link: '/cclub',
    companyClass: "claires",
    companyImage: '/claires_logo.png',
    companyAlt: "Claire's",
    companyLink: 'https://claires.com',
    blurb2:'I developed the entire fully responsive landing page',
    tech: 'Originally developed with HTML, CSS, and vanilla JavaScript; later rebuilt using React',
    funct: "User can find information regarding the Claire's reward program",
    videoTour:'hi',
    videoLink:'https://www.youtube.com/watch?v=VxTAagihZjQ&feature=youtu.be',
    bonusImg:'',
    bonusCaption: ""
  },
  {
    image: '/sandovalNew500.jpg',
    imageAlt: 'Sandoval Website',
    title: 'Sandoval Design & Marketing',
    subtitle: 'Official website for agency',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: '/cclub',
    companyClass: "sandoval",
    companyImage: '/sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:'I developed the entire fully responsive website',
    tech: 'PHP, Wordpress, Gravity Forms, Git, Gulp, SASS & HTML',
    funct: 'User can find information regarding the agency and contact the team',
    videoTour:'',
    bonusImg:'/fhlExtra300.jpg',
    bonusCaption: "*I'm also an extra in this movie and can be seen in the home page's video <i className='em em-sunglasses'></i>"
  },
  {
    image: '/wesco500two.jpg',
    imageAlt: 'WEScompany Website',
    title: 'WEScompany',
    subtitle: 'Official website for electrical company',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: 'http://wescompany.com/',
    companyImage: '/sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:'I developed the entire fully responsive website',
    tech: 'PHP, Wordpress, Gravity Forms, Gulp, SASS & HTML',
    funct: 'User can find information regarding WEScompany and contact their team',
    videoTour:'',
    bonusImg:'',
    bonusCaption: ""
  },
    {
    image: '/cclub.jpg',
    imageAlt: 'C.Club Landing Page',
    title: 'C.Club',
    subtitle: "Landing page for Claire's rewards program",
    blurb1: "Created while at Claire's",
    link: '/cclub',
    companyImage: '/claires_logo.png',
    companyAlt: "Claire's",
    companyLink: 'https://claires.com',
    blurb2:'I developed the entire fully responsive landing page',
    tech: 'Originally developed with HTML, CSS, and vanilla JavaScript; later rebuilt using React',
    funct: "User can find information regarding the Claire's reward program",
    videoTour:'',
    bonusImg:'',
    bonusCaption: ""
  },
  {
    image: '/sandovalNew500.jpg',
    imageAlt: 'Sandoval Website',
    title: 'Sandoval Design & Marketing',
    subtitle: 'Official website for agency',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: '/cclub',
    companyImage: '/sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:'I developed the entire fully responsive website',
    tech: 'PHP, Wordpress, Gravity Forms, Git, Gulp, SASS & HTML',
    funct: 'User can find information regarding the agency and contact the team',
    videoTour:'',
    bonusImg:'/fhlExtra300.jpg',
    bonusCaption: "*I'm also an extra in this movie and can be seen in the home page's video <i className='em em-sunglasses'></i>"
  },
  {
    image: '/wesco500two.jpg',
    imageAlt: 'WEScompany Website',
    title: 'WEScompany',
    subtitle: 'Official website for electrical company',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: 'http://wescompany.com/',
    companyImage: '/sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:'I developed the entire fully responsive website',
    tech: 'PHP, Wordpress, Gravity Forms, Gulp, SASS & HTML',
    funct: 'User can find information regarding WEScompany and contact their team',
    videoTour:'',
    bonusImg:'',
    bonusCaption: ""
  },
    {
    image: '/cclub.jpg',
    imageAlt: 'C.Club Landing Page',
    title: 'C.Club',
    subtitle: "Landing page for Claire's rewards program",
    blurb1: "Created while at Claire's",
    link: '/cclub',
    companyImage: '/claires_logo.png',
    companyAlt: "Claire's",
    companyLink: 'https://claires.com',
    blurb2:'I developed the entire fully responsive landing page',
    tech: 'Originally developed with HTML, CSS, and vanilla JavaScript; later rebuilt using React',
    funct: "User can find information regarding the Claire's reward program",
    videoTour:'',
    bonusImg:'',
    bonusCaption: ""
  },
];