export const PortfolioData = [
  {
    image: '/anova.jpg',
    imageAlt: 'Anova Website',
    title: 'Anova',
    subtitle: 'Official website for industrial assets company',
    blurb1: 'Created while at Bigfish Creative Group',
    link: 'https://www.anova.com/',
    companyClass: "bigfish",
    companyImage: './bigfish.jpg',
    companyAlt: 'Bigfish Creative Group',
    companyLink: 'https://www.linkedin.com/company/bigfish-creative-group/posts/?feedView=all',
    blurb2:'Collaboratively developed and maintained alongside another developer',
    tech: 'PHP, Wordpress, Gravity Forms, Git, Gulp, SASS &\u00A0HTML',
    funct: "Allows users to learn more about Anova and reach out to their team directly",
    videoTour:'',
    videoLink:'',
    bonusImg:'',
    bonusCaption: "",
    archived: ''
  },
  {
    image: '/wesco500two.jpg',
    imageAlt: 'WEScompany Website',
    title: 'WEScompany',
    subtitle: 'Official website for electrical company',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: 'http://wescompany.com/',
    companyClass: "sandoval",
    companyImage: './sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:'I developed the entire fully responsive website',
    tech: 'PHP, Wordpress, Gravity Forms, Gulp, SASS & HTML',
    funct: 'User can find information regarding WEScompany and contact their\u00A0team',
    videoTour:'',
    videoLink:'',
    bonusImg:'',
    bonusCaption: "",
    archived: ''
  },
  {
    image: '/cclub.jpg',
    imageAlt: 'C.Club Landing Page',
    title: 'C.Club',
    subtitle: "Landing page for Claire's rewards program",
    blurb1: "Created while at Claire's",
    link: '/cclub',
    companyClass: "claires",
    companyImage: '/claires_logo.png',
    companyAlt: "Claire's",
    companyLink: 'https://claires.com',
    blurb2:'I developed the entire fully responsive landing\u00A0page',
    tech: 'Originally developed with HTML, CSS, and vanilla JavaScript; later rebuilt using\u00A0React',
    funct: "User can find information regarding the Claire's reward\u00A0program",
    videoTour:'',
    videoLink:'',
    bonusImg:'',
    bonusCaption: "",
    archived: ''
  },
    {
    image: '/17elements500.jpg',
    imageAlt: '17 Elements Website',
    title: '17 Elements',
    subtitle: 'Official landing page for consulting company',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: 'http://17elements.com/',
    companyClass: "sandoval",
    companyImage: './sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:'I developed the entire fully responsive website',
    tech: 'ScrollReveal.js, Git, Gulp, CSS\u00A0&\u00A0HTML',
    funct: 'User can read about and contact the\u00A0company',
    videoTour:'1',
    videoLink:'https://www.youtube.com/watch?v=nTNNX86ZKUg',
    bonusImg:'',
    bonusCaption: "",
    archived: ''
  },
  {
    image: '/fhl500.jpg',
    imageAlt: 'Faith, Hope & Love Website',
    title: 'Faith, Hope & Love',
    subtitle: 'Official website for film',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: 'https://yohannisberg.github.io/fhl-reconstructed/',
    companyClass: "sandoval",
    companyImage: './sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:"I developed the entire fully responsive website in less than one week. Since promotion for this film has ended, the original site was taken down. Using web.archive.org and files I recovered from an old local drive, I’ve reconstructed it here for my\u00A0portfolio.",
    tech: 'PHP, Wordpress, Gravity Forms, Git, Gulp, SASS\u00A0&\u00A0HTML',
    funct: "User can find information regarding the film and contact the film's production company for further information",
    videoTour:'',
    videoLink:'',
    bonusImg:'fhlExtra300.jpg',
    bonusImgClass:'fhlBonus',
    bonusImgAlt:'Movie still of people dancing',
    bonusCaption: "*I can also be seen in the home page's video 😎",
    archived: ''
  },
  {
    image: '/adot.jpg',
    imageAlt: 'ADOT landing page',
    title: 'Arizona Department of Transportation',
    subtitle: 'Landing page for department of transportation',
    blurb1: 'Created while at Bigfish Creative Group',
    link: '/adot',
    companyClass: "bigfish",
    companyImage: './bigfish.jpg',
    companyAlt: 'Bigfish Creative Group',
    companyLink: 'https://www.linkedin.com/company/bigfish-creative-group/posts/?feedView=all',
    blurb2:'I developed the entire fully responsive landing\u00A0page',
    tech: 'SASS, HTML, Gulp & ScrollMagic.js',
    funct: 'User can find information regarding the Arizona Travel\u00A0ID',
    videoTour:'',
    videoLink:'',
    bonusImg:'',
    bonusCaption: "",
    archived: ''
  },
  {
    image: '/gcc500.jpg',
    imageAlt: 'GCC Website',
    title: 'Great Commission Collective',
    subtitle: 'Official website for church collective',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: 'https://yohannisberg.github.io/gcc-retrieval/',
    companyClass: "sandoval",
    companyImage: './sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:'I developed the entire fully responsive website in less than two weeks',
    tech: ' PHP, Wordpress, Gravity Forms, Git, Gulp, SASS\u00A0&\u00A0HTML',
    funct: 'User can find information regarding GCC and contact their\u00A0team',
    videoTour:'',
    videoLink:'',
    bonusImg:'gccConf.jpg',
    bonusImgClass:'gccBonus',
    bonusImgAlt:'John and co-workers at GCC conference',
    bonusCaption: "This website was launched at a GCC conference in Scottsdale, AZ",
    archived: ''
  },
  {
    image: '/cstudio.jpg',
    imageAlt: "Claire's C.Studio Website",
    title: "Claire's C.Studio",
    subtitle: "Landing page for Claire’s video series",
    blurb1: "Created while at Claire's",
    link: 'https://yohannisberg.github.io/cstudio/',
    companyClass: "claires",
    companyImage: '/claires_logo.png',
    companyAlt: "Claire's",
    companyLink: 'https://claires.com',
    tech: 'JavaScript, CSS\u00A0&\u00A0HTML',
    funct: "Users can watch the latest C.Studio episodes and shop stylist-curated products",
    videoTour:'',
    videoLink:'',
    bonusImg:'',
    bonusCaption: '',
    archived: ''
  },

  {
    image: '/gift-finder.jpg',
    imageAlt: "Claire's Gift Finder Component",
    title: "Claire's Gift Finder",
    subtitle: "Component developed for Claire’s website",
    blurb1: "Created while at Claire's",
    link: 'https://yohannisberg.github.io/gift-finder/',
    companyClass: "claires",
    companyImage: '/claires_logo.png',
    companyAlt: "Claire's",
    companyLink: 'https://claires.com',
    tech: 'JavaScript, CSS\u00A0&\u00A0HTML',
    funct: "Users can browse Claire’s holiday catalog to easily find the perfect gifts",
    videoTour:1,
    videoLink:'https://www.youtube.com/watch?v=Pu0gUwiGmj0',
    bonusImg:'',
    bonusCaption: "",
    archived: ''
  },
  {
    image: '/mvd.jpg',
    imageAlt: 'MVD Landing Page',
    title: 'AZ MVD Now',
    subtitle: "Landing page for ADOT's eTitle System",
    blurb1: 'Created while at Bigfish Creative Group',
    link: 'https://yohannisberg.github.io/mvd-lp/',
    companyClass: "bigfish",
    companyImage: './bigfish.jpg',
    companyAlt: 'Bigfish Creative Group',
    companyLink: 'https://www.linkedin.com/company/bigfish-creative-group/posts/?feedView=all',
    tech: 'CSS, HTML &\u00A0JavaScript',
    funct: 'User can read about online title transfer process',
    videoTour:'',
    videoLink:'',
    bonusImg:'',
    bonusCaption: "",
    archived: ''
  },
  {
    image: '/fixurelite.jpg',
    imageAlt: 'Fixturelite Website',
    title: 'Fixturelite',
    subtitle: 'Official website for retail solutions company',
    blurb1: 'Created while at Bigfish Creative Group',
    link: 'https://www.fixturelite.com/',
    companyClass: "bigfish",
    companyImage: './bigfish.jpg',
    companyAlt: 'Bigfish Creative Group',
    companyLink: 'https://www.linkedin.com/company/bigfish-creative-group/posts/?feedView=all',
    tech: 'PHP, Wordpress, Gravity Forms, Git, Gulp, SASS\u00A0&\u00A0HTML',
    funct: 'User can read about and contact the\u00A0company',
    videoTour:'',
    videoLink:'',
    bonusImg:'',
    bonusCaption: "",
    archived: ''
  },
  {
    image: '/sandoval500.jpg',
    imageAlt: 'Sandoval Website',
    title: 'Sandoval Design & Marketing',
    subtitle: 'Official landing page for agency',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: '',
    companyClass: "sandoval",
    companyImage: './sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:'I developed the entire fully responsive website',
    tech: 'ScrollReveal.js, Git, Gulp, CSS\u00A0&\u00A0HTML',
    funct: 'User can read about and contact the\u00A0company',
    videoTour:'1',
    videoLink:'https://www.youtube.com/watch?v=nTNNX86ZKUg',
    bonusImg:'',
    bonusCaption: "",
    archived: 1
  },
  {
    image: '/qualityFlix500.jpg',
    imageAlt: 'Pure Flix / Quality Flix Website',
    title: 'Pure Flix / Quality Flix',
    subtitle: 'Official page for film company',
    blurb1: 'Created while at Sandoval Design & Marketing',
    link: '',
    companyClass: "sandoval",
    companyImage: './sandovalLogo.png',
    companyAlt: 'Sandoval Design & Marketing',
    companyLink: 'https://sandovaldesign.com',
    blurb2:"I developed the Films and TV Series pages for Quality Flix's official website",
    tech: 'PHP, Wordpress, Gulp, SASS\u00A0&\u00A0HTML',
    funct: 'User can find information regarding the independent film company Quality\u00A0Flix',
    videoTour:'1',
    videoLink:'https://www.youtube.com/watch?v=VxTAagihZjQ',
    bonusImg:'',
    bonusCaption: "",
    archived: 1
  },
  {
    image: '/vimeo500.jpg',
    imageAlt: 'Vimeo Website',
    title: 'Vimeo.com (Partial Clone)',
    subtitle: 'Student project (Group)',
    blurb1: 'Created while studying at DevMountain',
    link: '',
    companyClass: "devmountain",
    companyImage: './devMtn.png',
    companyAlt: 'DevMountain',
    companyLink: 'https://devmountain.com',
    blurb2:"I designed the back-end endpoints and the front-end state management",
    tech: 'AngularJS, PostgreSQL, Node.js, Express.js, Git, Gulp, CSS\u00A0&\u00A0HTML',
    funct: 'User can sign in to their Vimeo account, upload/search videos, and post comments (comments posted through our clone will post on real Vimeo\u00A0website)',
    videoTour:'1',
    videoLink:'https://www.youtube.com/watch?v=YLsPgNy84p4',
    bonusImg:'',
    bonusCaption: "",
    archived: 1
  },
  {
    image: '/famVid500.jpg',
    imageAlt: 'Family Video Website',
    title: 'FamilyVideo.com (Partial Clone)',
    subtitle: 'Student project (Personal)',
    blurb1: 'Created while studying at DevMountain',
    link: '',
    companyClass: "devmountain",
    companyImage: './devMtn.png',
    companyAlt: 'DevMountain',
    companyLink: 'https://devmountain.com',
    blurb2:"For the accounts/shopping cart functionality, I created database tables utilizing a foreign key",
    tech: ' AngularJS, PostgreSQL, Git, Gulp, Node.js, Express.js, CSS\u00A0&\u00A0HTML',
    funct: ' User can create an account, sign in, search (items provided by Movie Database API), add/delete items from shopping cart, and empty shopping cart by going through a check out\u00A0process',
    videoTour:'1',
    videoLink:'youtube.com/watch?v=Dg6Btqb-wHw&feature=youtu.be',
    bonusImg:'champ.jpg',
    bonusImgClass: 'champ',
    bonusImgAlt:'John holding up a t-shirt',
    bonusCaption: 'Voted "Best Presentation"​ by DevMountain\'s staff',
    archived: 1
  },
];